// TODO: change these to enums once kame can do typescript enums (kame uses @babel/preset-typescript)

export type Key = string & { __type__: "Key" };
export const Key = {
  BACKSPACE: "BACKSPACE" as Key,
  DELETE: "DELETE" as Key,
  ENTER: "ENTER" as Key,
  TAB: "TAB" as Key,
  ESCAPE: "ESCAPE" as Key,
  UP: "UP" as Key,
  DOWN: "DOWN" as Key,
  RIGHT: "RIGHT" as Key,
  LEFT: "LEFT" as Key,
  HOME: "HOME" as Key,
  END: "END" as Key,
  PAGE_UP: "PAGE_UP" as Key,
  PAGE_DOWN: "PAGE_DOWN" as Key,
  F1: "F1" as Key,
  F2: "F2" as Key,
  F3: "F3" as Key,
  F4: "F4" as Key,
  F5: "F5" as Key,
  F6: "F6" as Key,
  F7: "F7" as Key,
  F8: "F8" as Key,
  F9: "F9" as Key,
  F10: "F10" as Key,
  F11: "F11" as Key,
  F12: "F12" as Key,
  F13: "F13" as Key,
  F14: "F14" as Key,
  F15: "F15" as Key,
  F16: "F16" as Key,
  F17: "F17" as Key,
  F18: "F18" as Key,
  F19: "F19" as Key,
  F20: "F20" as Key,
  F21: "F21" as Key,
  F22: "F22" as Key,
  F23: "F23" as Key,
  F24: "F24" as Key,
  COMMAND: "COMMAND" as Key,
  ALT: "ALT" as Key,
  CONTROL: "CONTROL" as Key,
  SHIFT: "SHIFT" as Key,
  RIGHT_SHIFT: "RIGHT_SHIFT" as Key,
  SPACE: "SPACE" as Key,
  PRINT_SCREEN: "PRINT_SCREEN" as Key,
  INSERT: "INSERT" as Key,
  VOLUME_DOWN: "VOLUME_DOWN" as Key,
  VOLUME_UP: "VOLUME_UP" as Key,
  MUTE: "MUTE" as Key,
  NUMPAD_0: "NUMPAD_0" as Key,
  NUMPAD_1: "NUMPAD_1" as Key,
  NUMPAD_2: "NUMPAD_2" as Key,
  NUMPAD_3: "NUMPAD_3" as Key,
  NUMPAD_4: "NUMPAD_4" as Key,
  NUMPAD_5: "NUMPAD_5" as Key,
  NUMPAD_6: "NUMPAD_6" as Key,
  NUMPAD_7: "NUMPAD_7" as Key,
  NUMPAD_8: "NUMPAD_8" as Key,
  NUMPAD_9: "NUMPAD_9" as Key,

  A: "A" as Key,
  B: "B" as Key,
  C: "C" as Key,
  D: "D" as Key,
  E: "E" as Key,
  F: "F" as Key,
  G: "G" as Key,
  H: "H" as Key,
  I: "I" as Key,
  J: "J" as Key,
  K: "K" as Key,
  L: "L" as Key,
  M: "M" as Key,
  N: "N" as Key,
  O: "O" as Key,
  P: "P" as Key,
  Q: "Q" as Key,
  R: "R" as Key,
  S: "S" as Key,
  T: "T" as Key,
  U: "U" as Key,
  V: "V" as Key,
  W: "W" as Key,
  X: "X" as Key,
  Y: "Y" as Key,
  Z: "Z" as Key,

  ZERO: "ZERO" as Key,
  ONE: "ONE" as Key,
  TWO: "TWO" as Key,
  THREE: "THREE" as Key,
  FOUR: "FOUR" as Key,
  FIVE: "FIVE" as Key,
  SIX: "SIX" as Key,
  SEVEN: "SEVEN" as Key,
  EIGHT: "EIGHT" as Key,
  NINE: "NINE" as Key,

  ANY: "ANY" as Key,
};

export type ModifierKey = string & { __type__: "ModifierKey" };
export const ModifierKey = {
  ALT: "ALT" as ModifierKey,
  COMMAND: "COMMAND" as ModifierKey,
  WINDOWS: "WINDOWS" as ModifierKey,
  SUPER: "SUPER" as ModifierKey,
  META: "META" as ModifierKey,
  CONTROL: "CONTROL" as ModifierKey,
  SHIFT: "SHIFT" as ModifierKey,
};

export type MouseButton = string & { __type__: "MouseButton" };
export const MouseButton = {
  LEFT: "LEFT" as MouseButton,
  RIGHT: "RIGHT" as MouseButton,
  MIDDLE: "MIDDLE" as MouseButton,

  ANY: "ANY" as MouseButton,
};
