// TODO: change these to enums once kame can do typescript enums (kame uses @babel/preset-typescript)

export type Key = string & { __type__: "Key" };
export const Key = {
  BACKSPACE: "BACKSPACE" as Key,
  DELETE: "DELETE" as Key,
  ENTER: "ENTER" as Key,
  TAB: "TAB" as Key,
  ESCAPE: "ESCAPE" as Key,
  UP: "UP" as Key,
  DOWN: "DOWN" as Key,
  RIGHT: "RIGHT" as Key,
  LEFT: "LEFT" as Key,
  HOME: "HOME" as Key,
  INSERT: "INSERT" as Key,
  END: "END" as Key,
  PAGE_UP: "PAGE_UP" as Key,
  PAGE_DOWN: "PAGE_DOWN" as Key,
  SPACE: "SPACE" as Key,

  F1: "F1" as Key,
  F2: "F2" as Key,
  F3: "F3" as Key,
  F4: "F4" as Key,
  F5: "F5" as Key,
  F6: "F6" as Key,
  F7: "F7" as Key,
  F8: "F8" as Key,
  F9: "F9" as Key,
  F10: "F10" as Key,
  F11: "F11" as Key,
  F12: "F12" as Key,
  F13: "F13" as Key,
  F14: "F14" as Key,
  F15: "F15" as Key,
  F16: "F16" as Key,
  F17: "F17" as Key,
  F18: "F18" as Key,
  F19: "F19" as Key,
  F20: "F20" as Key,
  F21: "F21" as Key,
  F22: "F22" as Key,
  F23: "F23" as Key,
  F24: "F24" as Key,

  LEFT_ALT: "LEFT_ALT" as Key,
  LEFT_CONTROL: "LEFT_CONTROL" as Key,
  LEFT_SHIFT: "LEFT_SHIFT" as Key,

  RIGHT_ALT: "RIGHT_ALT" as Key,
  RIGHT_CONTROL: "RIGHT_CONTROL" as Key,
  RIGHT_SHIFT: "RIGHT_SHIFT" as Key,

  LEFT_WINDOWS: "LEFT_SUPER" as Key,
  LEFT_COMMAND: "LEFT_SUPER" as Key,
  LEFT_META: "LEFT_SUPER" as Key,
  LEFT_SUPER: "LEFT_SUPER" as Key,

  RIGHT_WINDOWS: "RIGHT_SUPER" as Key,
  RIGHT_COMMAND: "RIGHT_SUPER" as Key,
  RIGHT_META: "RIGHT_SUPER" as Key,
  RIGHT_SUPER: "RIGHT_SUPER" as Key,

  PRINT_SCREEN: "PRINT_SCREEN" as Key,
  VOLUME_DOWN: "VOLUME_DOWN" as Key,
  VOLUME_UP: "VOLUME_UP" as Key,
  MUTE: "MUTE" as Key,
  PAUSE_BREAK: "PAUSE_BREAK" as Key,

  NUMPAD_0: "NUMPAD_0" as Key,
  NUMPAD_1: "NUMPAD_1" as Key,
  NUMPAD_2: "NUMPAD_2" as Key,
  NUMPAD_3: "NUMPAD_3" as Key,
  NUMPAD_4: "NUMPAD_4" as Key,
  NUMPAD_5: "NUMPAD_5" as Key,
  NUMPAD_6: "NUMPAD_6" as Key,
  NUMPAD_7: "NUMPAD_7" as Key,
  NUMPAD_8: "NUMPAD_8" as Key,
  NUMPAD_9: "NUMPAD_9" as Key,
  NUMPAD_MULTIPLY: "NUMPAD_MULTIPLY" as Key,
  NUMPAD_ADD: "NUMPAD_ADD" as Key,
  NUMPAD_SUBTRACT: "NUMPAD_SUBTRACT" as Key,
  NUMPAD_DECIMAL: "NUMPAD_DECIMAL" as Key,
  NUMPAD_DIVIDE: "NUMPAD_DIVIDE" as Key,
  NUMPAD_ENTER: "NUMPAD_ENTER" as Key,

  CAPS_LOCK: "CAPS_LOCK" as Key,
  NUM_LOCK: "NUM_LOCK" as Key,
  SCROLL_LOCK: "SCROLL_LOCK" as Key,

  SEMICOLON: "SEMICOLON" as Key,
  EQUAL: "EQUAL" as Key,
  COMMA: "COMMA" as Key,
  MINUS: "MINUS" as Key,
  PERIOD: "PERIOD" as Key,
  SLASH: "SLASH" as Key,
  BACKTICK: "BACKTICK" as Key,
  LEFT_BRACKET: "LEFT_BRACKET" as Key,
  BACKSLASH: "BACKSLASH" as Key,
  RIGHT_BRACKET: "RIGHT_BRACKET" as Key,
  QUOTE: "QUOTE" as Key,

  A: "A" as Key,
  B: "B" as Key,
  C: "C" as Key,
  D: "D" as Key,
  E: "E" as Key,
  F: "F" as Key,
  G: "G" as Key,
  H: "H" as Key,
  I: "I" as Key,
  J: "J" as Key,
  K: "K" as Key,
  L: "L" as Key,
  M: "M" as Key,
  N: "N" as Key,
  O: "O" as Key,
  P: "P" as Key,
  Q: "Q" as Key,
  R: "R" as Key,
  S: "S" as Key,
  T: "T" as Key,
  U: "U" as Key,
  V: "V" as Key,
  W: "W" as Key,
  X: "X" as Key,
  Y: "Y" as Key,
  Z: "Z" as Key,

  ZERO: "ZERO" as Key,
  ONE: "ONE" as Key,
  TWO: "TWO" as Key,
  THREE: "THREE" as Key,
  FOUR: "FOUR" as Key,
  FIVE: "FIVE" as Key,
  SIX: "SIX" as Key,
  SEVEN: "SEVEN" as Key,
  EIGHT: "EIGHT" as Key,
  NINE: "NINE" as Key,

  ANY: "ANY" as Key,
};

export type MouseButton = string & { __type__: "MouseButton" };
export const MouseButton = {
  LEFT: "LEFT" as MouseButton,
  RIGHT: "RIGHT" as MouseButton,
  MIDDLE: "MIDDLE" as MouseButton,

  ANY: "ANY" as MouseButton,
};
